package it.polimi.ingsw.Model.Cards;

public enum CharacterCardEnumeration {
    PLACE_ONE_STUDENT,
    TAKE_PROFESSOR_ON_EQUITY,
    FAKE_MN_MOVEMENT,
    TWO_EXTRA_ISLANDS,
    FORBID_ISLAND,
    TOWER_NO_VALUE,
    EXCHANGE_THREE_STUDENTS,
    TWO_EXTRA_POINTS,
    EXCLUDE_COLOUR_FROM_COUNTING,
    EXCHANGE_TWO_HALL_DINING,
    EXTRA_STUDENT_IN_DINING,
    REDUCE_COLOUR_IN_DINING
}
